/**
 * Created by Carson on 02/02/2017.
 */

"use strict";
module.exports = {

    tablename: "tablename",
    fields: "fields",
    table: "table",
    type: "type",
    default: "default",
    primaryKey: "primaryKey",
    operator: "operator",
    value: "value",
    true: "true",
    false: "false",
    undefined: "undefined",
    symbol: "symbol",
    object: "object",
    function: "function",
    number: "number",
    boolean: "boolean",
    string: "string",
    profile: "profile",
    to: "to",
    queensEmail: "@queensu.ca",
    needLogin: "needLogin",

    loginPage: "/login",
    aboutPage: "/about",
    newPage: "/new",
    listPage: "/list",
    profilePage: "/profile",
    guidelinesPage: "/guidelines",
    devPage: "/dev",
    evalPage: "/eval",
    helpPage: "/help",
    classPage: "/class",
    searchPage: "/search",
    logoutPage: "/logout",
    votePage: "/vote",
    subscribePage: "/subscribe",
    infoPage: "/info",
    landingPage: "/",

    zero: "0",
    one: "1",

    DESC: "DESC",
    desc: "desc",
    ASC: "ASC",
    asc: "asc",

    in: "in",
    between: "between",
    like: "like",

    host: "host",
    user: "user",
    secret: "secret",
    simpleSecret: "simplesecret",
    database: "database",
    maxConnections: "maxConnections",
    production: "production",
    databaseSetupNeeded: "databaseSetupNeeded",
    loadMockData: "loadMockData",
    utf8: "utf8",
    admin: "admin",
    userCookie: "usercookie",

    fieldUpvotes: "upvotes",
    fieldDownvotes: "downvotes",
    fieldNetvotes: "netVotes",
    fieldAuthor: "author",
    fieldID: "id",
    fieldContent: "content",
    fieldTimestamp: "timestamp",
    fieldUserID: "userID",
    fieldTitle: "title",
    fieldTags: "tags",
    fieldSummary: "summary",
    fieldItemID: "itemID",
    fieldType: "type",

    postTable: "post",
    fieldAnswered: "answered",

    commentTable: "comment",
    fieldIsSolution: "isSolution",
    fieldCommentLevel: "commentLevel",
    fieldParentPost: "parentPost",
    fieldParentComment: "parentComment",

    userTable: "user",
    fieldNetid: "netid",
    fieldUsername: "username",
    fieldTotalUpvotes: "totalUpvotes",
    fieldTotalDownvotes: "totalDownvotes",
    fieldTotalSolved: "totalSolved",
    fieldReportCount: "reportCount",
    fieldDateJoined: "dateJoined",
    fieldAcceptedTerms: "acceptedTerms",
    fieldPrivilege: "privilege",

    reportTable: "report",
    fieldReportReason: "reportReason",
    fieldReport: "report",
    fieldReportingUser: "reportingUser",
    fieldReportedUser: "reportedUser",
    fieldRelatedCommentOrPostID: "relatedCommentOrPostID",

    tagTable: "tag",
    fieldName: "name",
    fieldRelatedTags: "relatedTags",

    voteTable: "vote",
    fieldCommentOrPostID: "commentOrPostID",
    fieldVoteValue: "voteValue",

    sessionTable: "session",
    fieldSessionStart: "sessionStart",

    classTable: "class",
    fieldCourseCode: "courseCode",
    fieldLongSummary: "longSummary",

    link: "link",
    fieldTrusted: "trusted",
    fieldDateAdded: "dateAdded",
    fieldAddedBy: "addedBy",

    subscriptionsTable: "subscriptions",
    fieldLastNotified: "lastNotified",
    fieldNumNotificationsMissed: "numNotificationsMissed",
    fieldNumTimeNotified: "numTimesNotified",
    fieldDateSubscribed: "dateSubscribed",

    savedTable: "saved",
    fieldDateSaved: "dateSaved",

    contributionTable: "contribution",
    fieldDate: "date",

    sweeperCancelJob: "cancelJob",
    sweep: "sweep"
}